apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: Layer2-space
      protocol: layer2
      addresses:
      - 172.27.21.160-172.27.21.200
      avoid-buggy-ips: true
