apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: Layer2-space
      protocol: layer2
      addresses:
      #this range needs to be adapted to the environment! 
      #Choose something in the same subnet as the other k8s services (cluster-info)
      - 172.27.21.160-172.27.21.200 
      avoid-buggy-ips: true
